name: TrustShops
version: '${version}'
main: me.collinb.trustshops.TrustShops
api-version: '1.20'
author: 'collin-b1'
description: Unobtrusive, trust-based player shops
commands:
  tscreate:
    description: Register a container shop
    usage: /<command> <container_item> <container_amount> <player_item> <player_amount>
    aliases: [ shopcreate ]
  tsdelete:
    description: Unregister a container shop
    usage: /<command>
    aliases: [ shopdelete]
  tsinfo:
    description: Get information about a shop
    usage: /<command>
    aliases: [ shopinfo ]
  tsfind:
    description: Find shops for a specific item or by a player
    usage: /<command> <buying|selling|player> <item|player>
    aliases: [ shopfind ]
  tsreload:
    description: Reload TrustShops plugin
    usage: /<command>
    aliases: [ shopreload ]
    permission: trustshops.tsreload

permissions:
  trustshops.*:
    default: op
    description: Access to all TrustShop functions
  trustshops.all:
    default: op
    description: Access to all TrustShop functions
  trustshops.tsdelete.others:
    default: op
    description: Ability to delete other players shops